version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rinaldosilva.rule=Host(`rinaldosilva.com`)"
      - "traefik.http.routers.rinaldosilva.tls=true"
      - "traefik.http.routers.rinaldosilva.tls.certresolver=letsencrypt"
      - "traefik.http.services.rinaldosilva.loadbalancer.server.port=3000"

networks:
  default:
    external: true
    name: dokploy-network 