version: '1'

project:
  name: rinaldosilva-lp
  description: "Landing page do Rinaldo Silva"

services:
  app:
    type: application
    dockerfile: Dockerfile
    context: .
    
    # Configurações de build
    build:
      target: runner
      
    # Configurações de deployment
    deploy:
      replicas: 1
      restart_policy: unless-stopped
      
    # Health check
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
      
    # Recursos
    resources:
      limits:
        memory: 512M
        cpus: '0.5'
      reservations:
        memory: 256M
        cpus: '0.25'
        
    # Rede
    ports:
      - "3000:3000"
      
    # Variáveis de ambiente
    environment:
      NODE_ENV: production
      PORT: 3000
      HOSTNAME: "0.0.0.0"
      NEXT_TELEMETRY_DISABLED: 1
      
    # Labels para Traefik
    labels:
      traefik.enable: "true"
      traefik.http.routers.rinaldosilva.rule: "Host(`rinaldosilva.com`)"
      traefik.http.routers.rinaldosilva.tls: "true"
      traefik.http.routers.rinaldosilva.tls.certresolver: "letsencrypt"
      traefik.http.services.rinaldosilva.loadbalancer.server.port: "3000" 